# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
    - '2.7'
    - '3.5'

before_install:
    - pip install codecov

script:
    - make test

after_success:
  - codecov
